[build-system]
requires = [
    "hatchling>=0.13.0",
]
build-backend = "hatchling.build"

[project]
name = "datadog-akamai-cloud-pulse"
description = "Collect Akamai Cloud Pulse metrics with the Datadog Agent (unofficial)"
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.13"
keywords = [
    "datadog",
    "datadog agent",
    "datadog check",
    "akamai_cloud_pulse",
    "akamai",
    "linode",
]
authors = [
    { name = "ymori-aka" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: BSD License",
    "Private :: Do Not Upload",
    "Programming Language :: Python :: 3.13",
    "Topic :: System :: Monitoring",
]
dependencies = [
    "datadog-checks-base>=37.36.0",
]
dynamic = [
    "version",
]

[project.optional-dependencies]
deps = []

[project.urls]
Source = "https://github.com/ymori-aka/datadog-akamai-cloud-pulse"

[tool.hatch.version]
path = "datadog_checks/akamai_cloud_pulse/__about__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/datadog_checks",
    "/tests",
]

[tool.hatch.build.targets.wheel]
include = [
    "/datadog_checks/akamai_cloud_pulse",
]
dev-mode-dirs = [
    ".",
]
